added +3 days before functionality

diff --git a/backend/docker-compose.yml b/backend/docker-compose.yml
--- a/backend/docker-compose.yml
+++ b/backend/docker-compose.yml
@@ -39,6 +39,7 @@ services:
         environment:
             SUPABASE_URL: ${SUPABASE_URL}
             SUPABASE_API_KEY: ${SUPABASE_API_KEY}
+            TZ: Asia/Singapore
         develop:
             watch:
                 # Fast path: sync source edits into container
@@ -68,6 +69,7 @@ services:
             SUPABASE_URL: ${SUPABASE_URL}
             SUPABASE_API_KEY: ${SUPABASE_API_KEY}
             INTERNAL_API_KEY: ${INTERNAL_API_KEY}
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -95,6 +97,7 @@ services:
             SUPABASE_API_KEY: ${SUPABASE_API_KEY}
             SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
             SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -119,6 +122,7 @@ services:
         environment:
             SUPABASE_URL: ${SUPABASE_URL}
             SUPABASE_API_KEY: ${SUPABASE_API_KEY}
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -143,6 +147,7 @@ services:
         environment:
             INTERNAL_API_KEY: ${INTERNAL_API_KEY}
             KAFKA_BOOTSTRAP_SERVERS: kafka:9092
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -167,6 +172,7 @@ services:
         environment:
             INTERNAL_API_KEY: ${INTERNAL_API_KEY}
             KAFKA_BOOTSTRAP_SERVERS: kafka:9092
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -194,6 +200,7 @@ services:
         environment:
             INTERNAL_API_KEY: ${INTERNAL_API_KEY}
             KAFKA_BOOTSTRAP_SERVERS: kafka:9092
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -222,6 +229,7 @@ services:
             SMTP_PORT: ${SMTP_PORT}
             SMTP_USER: ${SMTP_USER}
             SMTP_PASS: ${SMTP_PASS}
+            TZ: Asia/Singapore
         develop:
             watch:
                 - action: sync
@@ -260,6 +268,7 @@ services:
             # Broker config
             KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
             KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+            KAFKA_NUM_PARTITIONS: 3
             KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # auto create topics if they don't exist
 
         healthcheck:
@@ -309,23 +318,23 @@ services:
             KAFKA_CLUSTERS_0_NAME: spm-cluster
             KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
 
-    kafka-setup:
-        image: apache/kafka-native:4.0.0
-        networks: [spm-net]
-        depends_on:
-            kafka:
-                condition: service_healthy
-        entrypoint:
-            - /bin/sh
-            - -lc
-            - |
-                echo "Waiting for kafka:9092..." ;
-                for i in $(seq 1 10); do
-                /usr/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1 && break ;
-                sleep 2 ;
-                done ;
-                echo "Creating topic notification-events if missing..." ;
-                /usr/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists \
-                --topic notification-events --partitions 1 --replication-factor 1 || true ;
-                echo "Done."
-        restart: "no"
+    # kafka-setup:
+    #     image: apache/kafka-native:4.0.0
+    #     networks: [spm-net]
+    #     depends_on:
+    #         kafka:
+    #             condition: service_healthy
+    #     entrypoint:
+    #         - /bin/sh
+    #         - -lc
+    #         - |
+    #             echo "Waiting for kafka:9092..." ;
+    #             for i in $(seq 1 10); do
+    #             /usr/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1 && break ;
+    #             sleep 2 ;
+    #             done ;
+    #             echo "Creating topic notification-events if missing..." ;
+    #             /usr/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists \
+    #             --topic notification-events --partitions 1 --replication-factor 1 || true ;
+    #             echo "Done."
+    #     restart: "no"
